name: steemit_sentinels
description: Official Steemit Sentinels App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ^0.12.0
  after_layout: ^1.0.7
  toast: ^0.0.6
  #lamp: ^0.0.6
  crypto: ^2.0.6
  local_notifications: ^0.0.7
  firebase_core: ^0.3.0+1
  firebase_database: ^2.0.1
  firebase_admob: ^0.8.0+1
  dio: ^1.0.13
  splashscreen: ^1.2.0
  flutter_launcher_icons: "^0.7.0"
  qr_code_scanner: ^0.0.2
  qr_flutter: ^1.1.5
  flutter_webview_plugin: ^0.3.0+2
  url_launcher: ^4.0.3
  #qr_reader: ^0.1.3
  path_provider: ^0.4.1
  sqflite: ^1.0.0
  pull_to_refresh: ^1.1.6
  #flutter_secure_storage: ^3.1.2
  #barcode_scan: ^0.0.8
  #qr: ^1.0.1
  flutter:
    sdk: flutter
  flutter_walkthrough:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/logo_stetemit_sentinels.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/loadingCircleGreen.gif
    - assets/loadingCircle.gif
    - assets/frame.png
    - assets/check_tick.gif
    - assets/flat_logo.png
    - assets/sync.gif
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

